module = "clicks"
uploadconfig = {
  update = true,
  pkg = "clicks",
  version = "0.3.1",
  author = "Yegor Bugayenko",
  uploader = "Yegor Bugayenko",
  email = "yegor256@gmail.com",
  note = "Bug fixes",
  announcement = "Some non-critical bug fixes",
  ctanPath = "/macros/latex/contrib/clicks",
  bugtracker = "https://github.com/yegor256/clicks/issues",
  home = "https://github.com/yegor256/clicks",
  description = "With the help of this package you can simulate animation in your slide deck, making it look similar to what PowerPoint can do.",
  development = "https://github.com/yegor256/clicks",
  license = "mit",
  summary = "Slide Deck Animation",
  repository = "https://github.com/yegor256/clicks",
  support = "https://github.com/yegor256/clicks",
  topic = {"emulation", "layout", "presentation"}
}