name: l3build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  l3build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: teatimeguest/setup-texlive-action@v3.3.3
        with:
          package-file: DEPENDS.txt
          update-all-packages: true
      - run: l3build check -q --show-log-on-error
